import React from 'react';
import Image from 'next/image'
import Head from "next/head";
import HomeHeroSection from '@/app/HomeHeroSection';

export default function Home() {
  return (
    <>
      <Head>
        <title>LOFICO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeHeroSection />
      </main>
    </>
  )
}
